### ISSUE TITLE
Remove daily index naming

### ISSUE THREAD

**Issue by kdotson3263k** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#101]
Hoping to get support/updates to remove the daily naming convention so that we can take advantage of ILM/rollover functions.

Any chance we can get an update/workaround for this?

**Comment by dstewart-broadsoft** [comment]
Just an option to be able to define a static name for the index?

**Comment by kdotson3263k** [comment]
Yes.  i.e ("bwlog"  without "-20200615") and "bwlog-(host)-apache" without "-20200615").

**Comment by dstewart-broadsoft** [comment]
I was thinking to add a parameter to the channel properties like :

channelfile:XSLog:/var/broadworks/logs/appserver:XSLog:*:**static:bwlog**

Whatever is in the last field will what will be the indexname. That work?

**Comment by kdotson3263k** [comment]
Yes.  That would be great.
