### ISSUE TITLE
MSFE logs not being parsed in sender

### ISSUE THREAD

**Issue by discotab311** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#16]
I've noticed that I am not getting any msfe logs from sender on the MS.

Reviewing the logging, in the .MSFe_persistfile.txt

[root@bms3 bwlogsender]# cat .MSFe_persistfile.txt
msfecontainerpmd02.log:0

For whatever reason, it doesn't seem to go any further, so none of the SIP msfe logs are added.  No issues on any of the other servers so far.

**Comment by dstewart-broadsoft** [comment]
Surprised this hadn't come up before.

On the MS - change the MS_channel.props file and change:

channelfile:MSFe:/var/broadworks/logs/mediaserver0:msfe:*:dailyperserver

to

channelfile:MSFe:/var/broadworks/logs/mediaserver0:msfe2:*:dailyperserver

(note the addition of a 2 to the 4th column)

stop the log sender - remove the persistfile - then start the sender - you should be good to go.

I'll update the package.

**Comment by discotab311** [comment]
Thanks Dave, worked like a champ.
