### ISSUE TITLE
bwlogreceiver throws a ClassCastException: Unsupported type: java.util.Hashtable shortly after starting

### ISSUE THREAD

**Issue by c-chaney** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#2]
- ProcessMonitor: Starting
2016-11-17_14:30:31.390 [ProcessMonitor] INFO  c.b.eslogzipshared.ProcessMonitor - Exception getting connection.
java.lang.ClassCastException: Unsupported type: java.util.Hashtable
        at javax.management.remote.rmi.RMIJRMPServerImpl$ExportedWrapper.check(RMIJRMPServerImpl.java:262)

**Comment by dstewart-broadsoft** [comment]
Are you using openJDK or Oracle's Java?

**Comment by c-chaney** [comment]
Oracle
java version "1.8.0_111"

**Comment by dstewart-broadsoft** [comment]
Ok.. I'd seen that with openJDK but never with Oracles. I  have an earlier version of 1.8 installed - pulling 111 now and will test.

**Comment by dstewart-broadsoft** [comment]
Reproduced it - will let you know when I've put a correction out.

**Comment by dstewart-broadsoft** [comment]
I've resolved it. I'll run a regression run tonight on both the latest jdk 1.7 and jdk 1.8 and post the updated bwlogreceiver package tomorrow morning.

**Comment by powershellnicholas** [comment]
Thanks for the update.

**Comment by dstewart-broadsoft** [comment]
New receiver package pushed out:

bwlogreceiver_621169.run

Let me know if you continue to have issues.

Thanks
Dave

**Comment by powershellnicholas** [comment]
Tested on JDK 1.8 - confirmed to be stable.
