### ISSUE TITLE
bwlogsender logic

### ISSUE THREAD

**Issue by kdotson3263k** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#38]
Hello,
If possible I would like some information regarding the logic of the bwlogsender.  I have a very active server with a large amount of stored PS and XS logs, I am concerned if I start the bwlogsender on this server it will attempt to read through and send all of the logs on the server.  Question is, how does the bwlogsender determine which files to send in a directory?  

I understand that the /usr/local/bwlogsender/bwlogsender/*.props determine which directory is used for the file source, I would like to understand how the files are read and sent so that I do not overwhelm the servers.

**Comment by kdotson3263k** [comment]
Hi,

I see a steady increase of ~20% utilization on one of the CPUs on the server since I started the bwlogsender application.  Is this expected?

What is the bwlogsender logic if the host server fails?  If the bwlogreveiver server fails?  If the network connection is lost?

It appears that the bwlogsender has a "X_persistentfile.txt" I assume this is used when the service is recovered?

Thanks,

kyle

**Comment by gokulbsft** [comment]
Every time when the bwlogsender is started, it looks for "X_persistfile.txt" file and resumes from the offset mentioned. In the absence of the X_persistfile.txt, it starts with the most recently modified log file of the list.

**Comment by bchibbard** [comment]
At present, it is not possible to do so, so a receiver must be deployed on a machine with enough resources that it can handle processing logs from at least one server. There can be multiple receivers to service multiple senders, but each sender can only send to one receiver. Are you having problems with the bwlogreceiver keeping up?

In the future we may be able to scale horizontally more easily as we expand our support for Kafka. To my knowledge, we haven't tested multiple receivers in the same Kafka topic/consumer group works, but with the right configuration, that may already work with the current release.

**Comment by kdotson3263k** [comment]
The receiver is keeping up, my concern is with redundancy.  If we have a receiver node outage, I would like to continue log flow until the node is restored.  If I am reading your response correctly, I think we would still have the same issue with the Kaftka configuration.  

I assume if it is possible to set up the sender to forward to both Kaftka and a receiver, then have a second receiver connect to the Kaftka instance we would duplicate data.

**Comment by kdotson3263k** [comment]
That is helpful because it does make the second leg (Kaftka -> receiver) redundant, but the leg between the sender and Kaftka is still single threaded.

**Comment by bchibbard** [comment]
I assume your concern is about availability, and not log throughput rate, correct?  Is your concern about whether bwlogsender (the process) dies, whether the box it runs on dies, or whether bwlogsender has no network path to the Kafka cluster?

**Comment by kdotson3263k** [comment]
Yes, in this case, my concern is availability (although the load is a consideration as well) and if there is no path to the Kafka cluster or the directly connected Kafka server fails.  

My preference would be to have two or more endpoints configured in the sender which would solve both connectivity and load concerns, although I would not want this at the expense of any additional significant load on the "bwlogsender" server.

**Comment by bchibbard** [comment]
Our current basic configuration tools don't (yet) expose configuration of multiple Kafka servers (which would presumably be members of the same cluster), but the Kafka client software we integrate with supports that.  With such a configuration, bwlogsender would then be able to write to whichever Kafka cluster members are available. Data written to Kafka would be replicated across the cluster, and processed by however many bwlogreceivers the topic configuration allows.  

Regarding performance, bwlogsender is designed more or less to use "spare resources" of the machine it is deployed on, so as not to impact product performance.  Fortunately, even under heavy test loads, what we've seen is that bwlogsender can keep up without interfering with the other server processes, while showing only a few seconds' worth of lag between the timestamp of the latest log and when the log is visible in Kibana.

**Comment by kdotson3263k** [comment]
If you update the logsender to expose the ability to send to multiple Kafka server that would meet my needs, although kafka adds a layer to the design.  

There also seems to be a limitation with the bwlogreceiver only able to interact with a single elasticsearch endpoint.  Is there any possible workaround to spread the traffic across multiple elasticsearch instances or at least failover for redundancy?


Thanks again for the feedback.

**Comment by kdotson3263k** [comment]
Just an FYI, I was able to alleviate most of my troubles by adding a load balancer between logsender and logreceiver and adding the logreceiver to each elasticsearch data server instance.  

I do have one more question, any chance you will be adding encryption methods for the sender?

Thanks again.

**Comment by bchibbard** [comment]
Hi,

We just added some TLS encryption between the log sender and receiver (not using Kafka). 

Eventually, we hope to add some richer configuration to allow the receiver to start with knowledge of multiple nodes of an elasticsearch cluster.

**Comment by kdotson3263k** [comment]
Thank you for the response!
