### ISSUE TITLE
BW Dashboard using Elasticsearch/Kibana v 5.1.1

### ISSUE THREAD

**Issue by aswil** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#4]
Hi,

I have installed Elasticsearch and Kibana v. 5.1.1
Elasticsearch is running, template loaded, bwlogsender and bwlogreceiver is running and data received by bwlogreceiver.
But data from bwlogreceiver can not be received by Elasticsearch:

java.lang.IllegalStateException: Received message from unsupported version: [2.0.0] minimal compatible version is: [5.0.0]

Is it possible to run Broadworks Dashboard with this Elasticsearch/Kibana version, perhaps with a new build of the bwlogreceiver?
Or do I have to install ElasticSearch v 2.3.3/Kibana v. 4.5.2?

BR

**Comment by dstewart-broadsoft** [comment]
At this time, the apps using the ES native client (bwlogreceiver is one of them) requires ES 2.3.3. We'll be releasing a new version early January with 5.x support and additionally be pushing the source for all the collectors here.

Dave

**Comment by aswil** [comment]
OK, thanks, I'll be looking for it.

BR

**Comment by htchang329** [comment]
Hi, Dave,
Is the ES 5.x support available now?

Thanks,
HC
