### ISSUE TITLE
bwlogsender/reciever not keeping up with heavy traffic load

### ISSUE THREAD

**Issue by kdotson3263k** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#41]
During busy hours on our more heavily loaded application server,  it looks like the bwlogsender/reciever is falling (corrected from failing to falling) behind the XSLog.  Can you suggest setting changes that may increase log processing speed for both the sender and receiver and the potential impact of the changes?

Thanks for the help.

**Comment by kdotson3263k** [comment]
Corrected a typo in the original Issue description.  Is anyone still watching this or is it a dead project?

**Comment by gokulbsft** [comment]
Did you install the sender and receiver with all the default values? Let us know if anything is modified from default values during installation.

**Comment by kdotson3263k** [comment]
receiver:
>>>Just updated "numbersenderwritethreads" from 1 to 24 with no change in behavior and I just changed "senderlogqueuesize" from 1000 to 2000 with no change.

enabled:true
servertype:AS
receiverserver:XX
receiverport:9072
kafkaserver:NA
kafkaport:9092
topicname:bwlog
topicgroup:sendgroup
usekafka:false
senderlogqueuesize:2000
numbersenderwritethreads:24
zipblocksize:8192
jvmheapsize:1024m
processmonitormaxthreads:100
processmonitormaxfiles:100
logsenderdebugging:false



bwlogreceiver:
elasticserver:XX
elasticport:9200
elasticclustername:ADV_VOICE
receiverport:9072
logprocessorqueuesize:200
logprocessornumthreads:4
jvmheapsize:1024m
JAVA_PATH:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.31-2.b13.el7.x86_64/bin/
ESAUTHUSER:NOAUTH
ESAUTHPASS:NOAUTH
kafkaserver:NA
kafkaserverport:9092
kafkastopicname:NA
kafkasgroupname:NA
usekafka:false

**Comment by kdotson3263k** [comment]
Can the sender keep up with 10+ MB of XSLogs /sec?
