### ISSUE TITLE
SIP Analyzer

### ISSUE THREAD

**Issue by kdotson3263k** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#50]
Hi,
I just started experimenting with SIP Analyzer again, and I am able to get my "List of Correlation ID" and "Complete Log :" when I click on the ID, but when I attempt to click the Correlation ID in the Complete log, the new SIP analyzer screen pops up with an "ERROR :( could not access server"  

**I see this in the Kibana stderr log:**

Debug: internal, implementation, error
    Error: connect ECONNREFUSED 0.0.0.0:5555
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

**stdout :**

{ host: '0.0.0.0',
  path: '/sipCallFlow?id=227e89a3-6c1b-48bc-826c-7b168c1202bf&index=bwlog*',
  port: '5555',
  method: 'GET' }
{"type":"error","@timestamp":"2018-06-11T22:45:37Z","tags":[],"pid":8244,"level":"error","error":{"message":"Uncaught error: connect ECONNREFUSED 0.0.0.0:5555","name":"Error","stack":"Error: connect ECONNREFUSED 0.0.0.0:5555\n    at Object.exports._errnoException (util.js:1020:11)\n    at exports._exceptionWithHostPort (util.js:1043:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)","code":"ECONNREFUSED"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":"?queryString=%2FsipCallFlow%3Fid%3D227e89a3-6c1b-48bc-826c-7b168c1202bf%26index%3Dbwlog*","query":{"queryString":"/sipCallFlow?id=227e89a3-6c1b-48bc-826c-7b168c1202bf&index=bwlog*"},"pathname":"/api/sip/sipCallFlowLogCollector","path":"/api/sip/sipCallFlowLogCollector?queryString=%2FsipCallFlow%3Fid%3D227e89a3-6c1b-48bc-826c-7b168c1202bf%26index%3Dbwlog*","href":"/api/sip/sipCallFlowLogCollector?queryString=%2FsipCallFlow%3Fid%3D227e89a3-6c1b-48bc-826c-7b168c1202bf%26index%3Dbwlog*"},"message":"Uncaught error: connect ECONNREFUSED 0.0.0.0:5555"}

**Comment by pgawali-broadsoft** [comment]
Hi ,
Looks like you didn't configure Logcollector for SIP plugin. Kindly run bwlogcollector and configure tribenode.json. for more details kindly refer section 4.5 Logcollector ( in  BroadWorks-Dashboards-and-Discovery/BroadWorks Dashboards and Discovery.pdf)

**Comment by kdotson3263k** [comment]
Hi, I do not see any instructions regarding tribenode.json in the BroadWorks-Dashboards-and-Discovery/BroadWorks Dashboards and Discovery.pdf, I also believe that tribe nodes are deprecated, do I need some other node set up?  


https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-tribe.html

"Warning
Deprecated in 5.4.0.
The tribe node is deprecated in favour of Cross Cluster Search and will be removed in Elasticsearch 7.0.)"

I have installed the bwlogcollector on the same server as I have the bwlogreceiver and it is configured and running per the instructions.  Can you provide any more details regarding the tribenode and what settings I am missing?

Thanks

**Comment by gokulbsft** [comment]
To clarify, tribenode.json is just the name of a file that contains the LogCollector address. 
The file is placed inside your Kibana installation location. (plugins/sip/tribenode.json)

This should contain the LogCollector address.
"javaClient": "<LOGCOLLECTOR_HOSTNAME_OR_IP>:5555"
For Ex: "javaClient": "localhost:5555" - If LogCollector is running in the same server where Kibana is installed.

By the way, we will include these steps in the document.

**Comment by tsanchez88** [comment]
Be sure to open the port "5555" on the server running the log collector software if you are running firewall software.

**Comment by kdotson3263k** [comment]
Thank you, that worked
