### ISSUE TITLE
subscriberdump error

### ISSUE THREAD

**Issue by kdotson3263k** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#52]
Hi trying to set up the subscriberdump and when running I am receiving the following error.  Can you point me in the a direction for what to look for?

./SubscriberExportDriver.pl
====== MAIN =======
**** OCI Client Build Version: 1.1.2
**** Start OCIClient initialization --> 2018.06.25 19:57:56:111 UTC
Exception: Server refused to register protocol, error code: 1
java.lang.Exception: Server refused to register protocol, error code: 1
        at com.broadsoft.clients.oci.bcct.BcctClient.connect(BcctClient.java:62)
        at com.broadsoft.clients.oci.OCIClient.connectToServer(OCIClient.java:410)
        at com.broadsoft.clients.oci.OCIClient.main(OCIClient.java:195)
Unable to connect to remote server with BCCT
java.lang.Exception: java.lang.Exception: Server refused to register protocol, error code: 1
Failed to disconnect from remote server with BCCT
java.lang.Exception: Failed to write packet:
**** Terminating **** OCI Client Build Version: 1.1.2 --> 2018.06.25 19:57:56:255 UTC

**Comment by bchibbard** [comment]
You would see this error for sure if you did not add the host/IP to the OCI-P ACL on the target AS.

**Comment by kdotson3263k** [comment]
Great thanks, I got it working except I am receiving an invalid login ID, I am then prompted for the password for the AS, I enter the same password I put into the config file and the subscriberdump completes the download and ingestion,
