### ISSUE TITLE
bwlogreceiver_1021 - Help with SSL

### ISSUE THREAD

**Issue by kdotson3263k** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#53]
Hello,
I need some help with the next steps.  

I have ordered certs for one of the bwlogreceiver servers and added the certs to the server.  I then gernerated the pkcs12 file with the following:

openssl pkcs12 -export -out servername.pfx -inkey server.key -in signed_cert.crt

updated the "logreceiver.props"  with:

senderreceiverusessl: true
truststorepath:/cert_directory
truststorepassword:XXXXXXX

then restarted.

Looks like connection is closing:

2018-07-25_17:43:41.646 [LogReceiver: 96.114.121.197] INFO  c.b.eslogzipreceiver.NetworkSocket - Got general Exception from BufferedReader().readLine()
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake

**Comment by bchibbard** [comment]
There's a few things.

1. The log you see is the receiver expecting TLS from the sender, and it isn't getting it.  The "senderreceiverusessl" is purely for between the sender and the receiver.  They both must be set the same, and neither of them use certs (yet) as the connection is not being authenticated, only encrypted.

2. Certs are (so far) only used when connecting to elasticsearch.  [ If that applies to you, read on ... ]

3. The file that contains the cert ought to be for the signing authority (root CA)  you used for making your ES certs when you turned on security.  The cert(s) should be imported into  a Java "keytool" keystore/truststore file.  See section 3.1.3.

4. The path to the truststore is not a directory, but the full pathname of the truststore file mentioned above.

**Comment by kdotson3263k** [comment]
Hi bchibbard, thanks for the response, I will be enabling elasticsearch security, but would like to work through sender to receiver issue first.

Sorry if this is an ingnorant question, but you said in #1 "They both must be set the same" I do not see a setting on logsender, is there something else I have to enable on the logsender side?

**Comment by kdotson3263k** [comment]
Having trouble getting this working any help will be appreciated.  

Also, do you guys put out any release note info would like to know what was changed in 1021?

Thanks

**Comment by bchibbard** [comment]
Yes, there also is "senderreceiverusessl" in the sender.  That property needs to be set to the same value in both sender and receiver.  Is the sender the same version as the receiver?  

We don't yet do release notes, but hopefully will someday.  It definitely would be handy.

**Comment by kdotson3263k** [comment]
Thanks bchibbard,
I do not see that property in the "logsender.props".  I am using "bwlogsender -> /usr/local/bwlogsender/bwlogsender_1021"

which is the same as the receiver.  Is this a property I can add in?

**Comment by kdotson3263k** [comment]
I have added "senderreceiverusessl:true" in the logsender.props and changed senderreceiverusessl from false to true in the logreceiver.props then restarted each.  Logging into elasticsearch is good but I am not sure data is encrypted between sender and receiver.  I will perform a tcpdump,  but want to make sure these are the correct settings.

Thanks

**Comment by kdotson3263k** [comment]
I just validated that this is working...closing.

Thanks again for your support!
