### ISSUE TITLE
Separate AuditLog entries

### ISSUE THREAD

**Issue by coreyt429** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#56]
At present AuditLog entires go into bwlog-*.   Would it be possible to put them into a separate index like apache logs?  This would give us the ability to keep AuditLogs searchable indefinitely, instead of losing them when we DELETE the oldest bwlog-YYMMDD.

**Comment by jmanuta** [comment]
You need to edit your AS_channel.props file so that AuditLog is set to "daily" instead of the default "dailyallserver"

channelfile:AuditLog:/var/broadworks/logs/appserver:AuditLog:*:daily

Once you restart the logsender, you'll see a separate index for bwlog-as1-auditlog-YYYYMMDD

**Comment by coreyt429** [comment]
Thanks Jason,  that is perfect.
