### ISSUE TITLE
Can bwlog be more granular

### ISSUE THREAD

**Issue by coreyt429** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#57]
bwlog currently gets created in a daily index, which is ~700GB per day and growing.  Is this configurable now?  Could I do hourly indexes instead, or would that make the shards too small?

**Comment by jmanuta** [comment]
If all your logs are going into bwlog-YYYYMMDD, you could set the  server's _channel.props file so that each channel is set to "dailyperserver" instead of "dailyallserver".  This would then give you bwlog-as1-YYYYMMDD, bwlog-xsp1-YYYYMMDD, bwlog-ps1-YYYYMMDD, etc.

**Comment by coreyt429** [comment]
Agreed. I'll try that first.  My only concern here is that 90% of my current logging is from one AS cluster.  I started with the least busy clusters, then added one of our 3 busiest clusters to test the system.  performance is acceptable right now.  The only time the large indexes seems to be a problem is if we add or remove a data node, and a shard has to be rebuilt from a replica.  That process takes a couple of hours in the evening as those indexes are full.  I've partially mitigated that by increasing the shard count.

I also feel like hourly would probably just be too many indexes and shards.
