### ISSUE TITLE
Two index per node

### ISSUE THREAD

**Issue by kdotson3263k** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#59]
Hi,

I am currently set to "dailyallserver" in my bwlogsender props for all files, but I am seeing two indexes:

bwlog-"date broken down by day"
and
bwlog-"node"-apache-"date broken down by month"

Is this by design?  Can I combine?

Thanks!

**Comment by kdotson3263k** [comment]
The other issue I see with this is that the "apache" index is getting double the shard allocation.

I am sitting at 100 shards per day on the non-apache index which is currently too large and needs to be adjusted down, but the apache index is at 200 shards at one-tenth of the size, can someone help me with a strategy?

I also noticed that when I try to update the template to lower shard count, the template updates, but the index created the next day still has the same number of shards.  Elasticsearch problem? 

Thanks for any help.

**Comment by kdotson3263k** [comment]
**Still looking for any info on this:**

Here is the output of my "AS_channel.props"
channelfile:XSLog:/var/broadworks/logs/appserver:XSLog:*:dailyallserver
channelfile:PSLog:/var/broadworks/logs/appserver:PSLog:*:dailyallserver
channelfile:AuditLog:/var/broadworks/logs/appserver:AuditLog:*:dailyallserver
channelfile:OCSLog:/var/broadworks/logs/openclientserver:OCSLog:*:dailyallserver
channelfile:CommPilot:/var/broadworks/logs/appserver/CommPilotLog:CommPilotLog:*:dailyallserver
channelfile:MediaFiles:/var/broadworks/logs/appserver/MediaFilesLog:MediaFilesLog:*:dailyallserver
channelfile:JWSFiles:/var/broadworks/logs/appserver/JWSFilesLog:JWSFilesLog:*:dailyallserver
channelfile:DeviceManagementFiles:/var/broadworks/logs/appserver/DeviceManagementFilesLog:DeviceManagementFilesLog:*:dailyallserver
channelfile:OCIFiles:/var/broadworks/appserver/logs/OCIFiles:OCIFilesLog:*:dailyallserver
channelfile:Apache:/var/broadworks/logs/apache:access_log:*:dailyallserver

# Platform Channels
channelfile:SWManager:/var/broadworks/logs/swmanager:swmanagerActivities:*:dailyallserver
channelfile:ConfigAgent:/var/broadworks/logs/config:configd2:*:dailyallserver
channelfile:LicenseManager:/var/broadworks/logs/lmd:lmLog:*:dailyallserver
channelfile:SNMP:/var/broadworks/logs/snmp:snmp:*:dailyallserver

**but I am still seeing:**
both a daily "bwlog-201811XX"

**and a monthly apache for every node**
bwlog-wdv-asXX-XX-apache-201811

**Comment by gokulbsft** [comment]
Does this duplicate entry present for all the application? Or is it specific to apache?
Do the similar indices appear for every month?

I do have a setup with "dailyallserver" that gives me only one index per day. I do not see any monthly index in the list.

I am just curious to know when or how the monthly basis index is created?

**Comment by kdotson3263k** [comment]
It is not really a duplicate, sorry if I miss lead, I have an apache index for every node, and a bwlog-2018MMDD that all nodes index into.

They do appear every month.


here is an example:

bwlog-20181115
bwlog-20181116
bwlog-20181117
bwlog-20181118
bwlog-20181119
bwlog-20181120
bwlog-20181121
bwlog-20181122
bwlog-20181123
bwlog-wdv-as08-01-apache-201810
bwlog-wdv-as08-01-apache-201811
bwlog-wdv-as08-02-apache-201810
bwlog-wdv-as08-02-apache-201811
bwlog-wdv-as11-01-apache-201810
bwlog-wdv-as11-01-apache-201811
bwlog-wdv-as11-02-apache-201810
bwlog-wdv-as11-02-apache-201811
bwlog-wdv-as12-01-apache-201810
bwlog-wdv-as12-01-apache-201811
bwlog-wdv-as12-02-apache-201810
bwlog-wdv-as12-02-apache-201811

**Comment by kdotson3263k** [comment]
You can see from the previous comment that AS08-01 is one of the servers with this issue, here is the channel props file from that AS.

bwadmin@wdv-as08-01$ cat /usr/local/bwlogsender/bwlogsender/AS_channel.props
channelfile:XSLog:/var/broadworks/logs/appserver:XSLog:*:dailyallserver
channelfile:PSLog:/var/broadworks/logs/appserver:PSLog:*:dailyallserver
channelfile:AuditLog:/var/broadworks/logs/appserver:AuditLog:*:dailyallserver
channelfile:OCSLog:/var/broadworks/logs/openclientserver:OCSLog:*:dailyallserver
channelfile:CommPilot:/var/broadworks/logs/appserver/CommPilotLog:CommPilotLog:*:dailyallserver
channelfile:MediaFiles:/var/broadworks/logs/appserver/MediaFilesLog:MediaFilesLog:*:dailyallserver
channelfile:JWSFiles:/var/broadworks/logs/appserver/JWSFilesLog:JWSFilesLog:*:dailyallserver
channelfile:DeviceManagementFiles:/var/broadworks/logs/appserver/DeviceManagementFilesLog:DeviceManagementFilesLog:*:dailyallserver
channelfile:OCIFiles:/var/broadworks/appserver/logs/OCIFiles:OCIFilesLog:*:dailyallserver
channelfile:Apache:/var/broadworks/logs/apache:access_log:*:dailyallserver

# Platform Channels
channelfile:SWManager:/var/broadworks/logs/swmanager:swmanagerActivities:*:dailyallserver
channelfile:ConfigAgent:/var/broadworks/logs/config:configd2:*:dailyallserver
channelfile:LicenseManager:/var/broadworks/logs/lmd:lmLog:*:dailyallserver
channelfile:SNMP:/var/broadworks/logs/snmp:snmp:*:dailyallserver

**Comment by gokulbsft** [comment]
Got it!

This is as per the design and can not be combined.

Additionally, the Apache indices can be created on a daily basis (instead of a monthly basis as you set now) by setting "daily" for apache's channel file.
Ex : channelfile:Apache:/var/broadworks/logs/apache:access_log::daily

**Comment by kdotson3263k** [comment]
ok thanks. 

My issue is that I have increased the number of shards on the log_template.json and the apache index does not require the larger number of shards.  

Can you suggest a modification to the template or the index so that I can set the number of shards for the apache index independently of the bwlog* index?

Thanks

**Comment by gokulbsft** [comment]
Below customization steps can help you,

Copy the file "log_template.json" to "log_template_apache.json".
In log_template_apache.json, 
Set **"template": "bwlog*apache*"** and **"number_of_shards": "<Required Value>"**

Add below line to the file "log_template.pl" (just before the last exit call),
system("curl -sS -H \"Content-Type: application/json\" --data \@log_template_apache.json -XPUT $hostname:9200/_template/log_record_apache?pretty");

9200 - ElasticServer port.

Run log_template.pl.

**Comment by kdotson3263k** [comment]
This worked great thank you!!!!

just one note need "\" before the "@" and quotes in the log_template.pl system call.
