### ISSUE TITLE
Huge bwlogs under elasticsearch

### ISSUE THREAD

**Issue by alvperezm** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#6]
Hello,

After installing kibana/elasticsearch for broadworks trying to start elasticsearch indices, received error:

Starting elasticsearch: OpenJDK 64-Bit Server VM warning: Insufficient space for shared memory file

Double checked /var/lib directory to verify storage and got 17G under elasticsearch index

[root@localhost lib]# du -sh /var/lib/*
44K     /var/lib/alternatives
40K     /var/lib/authconfig
8.0K    /var/lib/dbus
4.0K    /var/lib/dhclient
17G     /var/lib/elasticsearch
4.0K    /var/lib/fprint
4.0K    /var/lib/games
4.0K    /var/lib/logrotate.status
4.0K    /var/lib/misc
2.3M    /var/lib/mlocate
16K     /var/lib/net-snmp
4.0K    /var/lib/ntp
8.0K    /var/lib/plymouth
28K     /var/lib/polkit-1
4.0K    /var/lib/postfix
12K     /var/lib/prelink
4.0K    /var/lib/random-seed
4.0K    /var/lib/readahead
67M     /var/lib/rpm
4.0K    /var/lib/rsyslog
36K     /var/lib/sss
12K     /var/lib/stateless
8.0K    /var/lib/udev
7.3M    /var/lib/yum

Bwlogs from AS are huge:

[root@localhost 0]# du -sh /var/lib/elasticsearch/companydd/nodes/0/indices/*
76M     /var/lib/elasticsearch/companydd/nodes/0/indices/bwcdr
136K    /var/lib/elasticsearch/companydd/nodes/0/indices/bwlog-appservbrst1-20170120
120K    /var/lib/elasticsearch/companydd/nodes/0/indices/bwlog-appservbrst1-20170121
120K    /var/lib/elasticsearch/companydd/nodes/0/indices/bwlog-appservbrst1-20170122
120K    /var/lib/elasticsearch/companydd/nodes/0/indices/bwlog-appservbrst1-20170123
124K    /var/lib/elasticsearch/companydd/nodes/0/indices/bwlog-appservbrst1-20170124
220K    /var/lib/elasticsearch/companydd/nodes/0/indices/bwlog-appservbrst1-20170125
120K    /var/lib/elasticsearch/companydd/nodes/0/indices/bwlog-appservbrst1-20170126
120K    /var/lib/elasticsearch/companydd/nodes/0/indices/bwlog-appservbrst1-20170127
544K    /var/lib/elasticsearch/companydd/nodes/0/indices/bwlog-appservbrst1-20170128
3.7M    /var/lib/elasticsearch/companydd/nodes/0/indices/bwlog-appservbrst1-20170129
3.9M    /var/lib/elasticsearch/companydd/nodes/0/indices/bwlog-appservbrst1-20170130
3.5G    /var/lib/elasticsearch/companydd/nodes/0/indices/bwlog-appservbrst1-20170131
9.7G    /var/lib/elasticsearch/companydd/nodes/0/indices/bwlog-appservbrst1-20170201
3.2G    /var/lib/elasticsearch/companydd/nodes/0/indices/bwlog-appservbrst1-20170202
4.6M    /var/lib/elasticsearch/companydd/nodes/0/indices/bwlog-appservbrst1-apache-201701
13M     /var/lib/elasticsearch/companydd/nodes/0/indices/bwlog-appservbrst1-apache-201702

After deleting the following files, we were able to get kibana and elasticsearch running and have dashboards working again

3.5G    /var/lib/elasticsearch/companydd/nodes/0/indices/bwlog-appservbrst1-20170131
9.7G    /var/lib/elasticsearch/companydd/nodes/0/indices/bwlog-appservbrst1-20170201
3.2G    /var/lib/elasticsearch/companydd/nodes/0/indices/bwlog-appservbrst1-20170202

Is there any way to fix this issue?

Thanks in advance

**Comment by dstewart-broadsoft** [comment]
How much disk space do you have? Usually the shared memory file is in /tmp

What does your df look like?

**Comment by alvperezm** [comment]
Hi Dave,

Below df output:
[root@localhost /]# df -h
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/vg.01-root
                       20G  8.8G  9.9G  47% /
tmpfs                 5.8G     0  5.8G   0% /dev/shm
/dev/sda2              93M   55M   34M  63% /boot
/dev/sda1             200M  260K  200M   1% /boot/efi
/dev/mapper/vg.01-bw  256G   60M  243G   1% /bw


Thank you

**Comment by dstewart-broadsoft** [comment]
First off, yes, BroadWorks generates A LOG of logs - not surprising you are generating large daily indexes. I noticed from the above that you are using the / partition which only has 20G - but you have a /bw partition with 243G free? (this is assuming that this is no longer a BroadWorks node - hopefully). The benefit of moving to /bw means if you run out of space again it won't hose the OS - I.E. apps not being able to create SHM files. If you need assistance with the config for ES for moving the data to a different partition, let me know and I'll assist.

**Comment by alvperezm** [comment]
We can use /bw partition, this server is not part of our Boradworks platform, just created that that partition with that name, can you please send me the steps for moving data to this partition? it is possible to zip this files? because at some point, it is going to happen over the new partition.

**Comment by dstewart-broadsoft** [comment]
I discussed the configuration a bit in section 3.1.2 - specifically discussing path.data. A more thorough discussion on the topic is here:

https://www.elastic.co/guide/en/elasticsearch/reference/2.0/setup-dir-layout.html

Essentially shutdown elasticsearch - change the config/elasticsearch.yml file - move the files if you wish to retain the current collected logs - then restart elasticsearch. Watch the ES logs as it start to ensure it finds the indexes.

As for ziping the files - if you used the included index template with bwlogreceiver - it is already using compressed indexes so it is as small as it will get. Logs take space - each document (which is a broadworks log) includes parsed out search terms (for search speed) and the whole log (for reproducing logs when troubleshooting) which means the documents themselves are relatively large - although through my testing and validation - using compressed indexes actually makes the collection of documents for a specific file smaller than the original text log file.

**Comment by alvperezm** [comment]
OK David, let me work on this and let you know tomorrow how does it goes.
