### ISSUE TITLE
ID search not pulling in the MS logs (msfe)

### ISSUE THREAD

**Issue by kdotson3263k** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#61]
When I search with the Correlation ID in the SIP Analyzer-> ID search, I do not see the associated MS logs.  
I am able to search for and find the logs using Kibana Discover "server is ms" and correlation ID in quotes.

**Comment by kdotson3263k** [comment]
Thank you.

I am sure you have already thought of this, but many of the logs in the MS (and other platforms) do not contain the Correlation ID but are related to the transaction via another field, such as the Call ID, will you also be using other fields to pull in all associated records?

**Comment by gokulbsft** [comment]
Yes. The "Advanced Search" option in SIP Analyzer will get them also.
