### ISSUE TITLE
Log Collector - More specific on Usernames

### ISSUE THREAD

**Issue by kdotson3263k** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#62]
Can you please give me a bit more specifics on the Usernames for the Log Collector/OCI Transactions?

Admin Username?  - Is this the OS level admin?
Query Username?  bwcli user, database user??
System Username - again not sure what this is.

Currently when I try to log collect is just sits there spinning the "Loading...", no error, but nothing is changing.

Thanks.

**Comment by Rakesh100908** [comment]
Admin Username  : BroadWorks Administrator ( i.e. admin UserID used to login to CLI or Portal)
Query Username   : BroadWorks  User (Target user for which query is performed)
System Username :  OS Level User (User ID used for ssh for e.g. default user : bwadmin)
