### ISSUE TITLE
6.7 Support?

### ISSUE THREAD

**Issue by Zeal0us** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#71]
Any plans to add the 6.7 version of the plugins?  I'm hoping to install the SIP analyzer pretty soon, but we are on the newest version of ES.

**Comment by IshMalik** [comment]
+1 for this question.

And is there any roadmap for 6.8 support?

**Comment by Rakesh100908** [comment]
Closing this one...
as latest ones are released
7.6.0, 7.6.1,7.6.2
