### ISSUE TITLE
Support for 7.x

### ISSUE THREAD

**Issue by MistAssassin** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#78]
Looking to see if 7.x support is on the roadmap.

**Comment by ounorton** [comment]
Would be interested if there is a roadmap...

**Comment by gokulbsft** [comment]
SIP and XSI Plugins for ES 7.0.1 and 7.1.1 are available at 
https://github.com/BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery

Note: Latest log receiver (bwlogreceiver_1204.run) should be used for ES 7.

**Comment by MistAssassin** [comment]
Thanks for the update.
I was wondering if it's possible to get a 7.2.x plugin update? With Elastic making Security features free in that version, I'd ideally like to be able to deploy 7.2.

**Comment by RaceAap** [comment]
As ES 7.1.x has an eol at 2020-11-20 when will you update the plugins to version 7.4.x ?

**Comment by gokulbsft** [comment]
7.4.x is already released.

**Comment by ounorton** [comment]
Any plan for a 7.6.x plugin release?

**Comment by Rakesh100908** [comment]
7.6.x were released today
