### ISSUE TITLE
bwlogreceiver - Trouble detecting Java Executable

### ISSUE THREAD

**Issue by jessiebryan** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#8]
As root, I am running the interactive installer from bwlogreceiver_jb-114.run.  At the prompt for ''What is the path to the Java Executable:'' I am not given an autocompleted response, and when I enter the full path (in my case /usr/java/jre1.8.0_121/bin/java), the installer repeats the question over and over.

System details:
`CentOS 7 64bit running Java Version: jre1.8.0_121-1.8.0_121-fcs.x86_64
 64GB RAM, 20 CPUs`

`[root@bwdash]# java -showversion
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
`

Output of running bwlogreceiver as well as some output for java version: [https://hastebin.com/rowofuwico.txt](url)

Is CentOS 7 and Oracle JRE 1.8.0 supported?

**Comment by aravindtga** [comment]
Did you tried with this path `/usr/java/jre1.8.0_121/bin/` ?

**Comment by jessiebryan** [comment]
..sigh, I was using the binary not the path. Thanks @aravindtga 

All good.
