### ISSUE TITLE
bwlogreceiver issues

### ISSUE THREAD

**Issue by bfortune2** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#80]
I'm struggling to get my bwlogsender and bwlogreceiver talking for some reason and I don't see exactly what the issue is.  I've configured the bwlogreceiver on the same server and ES.  I've been able to manually load XSLog files by utilizing the bwlogfileprocessor.  However, when I attempt to turn on the bwlogsender on an AS and send directly to the 9072 port on the elastic search server with bwlogreceiver running I get an error on the collector side that says:
2019-08-21_07:50:11.224 [Sender Thread #0] INFO  c.broadsoft.zipsender.NetworkSocket - Connection attempt to Receiver failed (ConnectionException)
2019-08-21_07:50:16.224 [Sender Thread #0] INFO  c.broadsoft.zipsender.NetworkSocket - Attempting to create socket to Receiver

I can run TCPDump on the ES server and I see the AS getting to the ES with the 9072 port.  bwlogreceiver appears to be running and I'm not seeing any issues:
elastic@ess1 bwlogreceiver]$ ./bwlogreceiver.pl --showrun

Log Receiver is running as pid 14827

Here's the logreceiver props file:
[elastic@ess1 bwlogreceiver]$ cat logreceiver.props
##
##
elasticserver:127.0.0.1
##
##
elasticport:9200
##
##
elasticclustername:bwc4
##
##
receiverport:9072
##
##
senderreceiverusessl:false
##
##
logprocessorqueuesize:200
##
##
logprocessornumthreads:8
##
##
jvmheapsize:1024m
##
##
##
JAVA_PATH:/usr/local/java/java_base/bin
##
## Leave default (NOAUTH) if not utilizing authentication
ESAUTHUSER:NOAUTH
##
## Leave default (NOAUTH) if not utilizing authentication
ESAUTHPASS:NOAUTH
##
## Truststore must be a JKS or PKCS12 file.
truststorepath:elastic
##
##
truststorepassword:elastic
##
##
kafkaserver:None
##
## 
kafkaserverport:9092
##
## 
kafkastopicname:None
##
## 
kafkasgroupname:None
##
## 
usekafka:false
[elastic@ess1 bwlogreceiver]$ 

I'm not sure what's going on.  It has to be something simple, but I've been looking at this I can't figure it out.  Would welcome any assistance I can get.  :-)

**Comment by dstewart-broadsoft** [comment]
I would check iptables on the ES host - most of the distributions are securing the interfaces by default these days... Check "iptables --list" as root.

You can kill the iptables configuration by doing a "iptables --flush" to verify.

**Comment by bfortune2** [comment]
Thank you Dave.  That was it!
