### ISSUE TITLE
Call flow SVG not rendering

### ISSUE THREAD

**Issue by natecriss** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#84]
We are able to view the SIP messages associated with a correlation ID in both the home section and the ID search section but when we attempt to view the SIP Ladder in the call flow nothing is displayed. 

It looks like mscgen.js isn't being called or the mscgen code isn't being passed correctly (or at all) in our installation.  The SVG generated contains the following error message:

> This page contains the following errors:
> error on line 1 at column 1599: Extra content at the end of the document
> Below is a rendering of the page up to the first error.

and when viewed the source of the SVG is as follows:

  ```html
<div id="__chart" class="mscgen_js" data-language="x-xu" style="display: inline-block;"> <svg version="1.1" id="mscgenjs__chart" class="mscgenjs__chart" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="16" height="82" viewBox="0 0 16 82"><defs><style type="text/css">svg.mscgenjs__chart{font-family:Helvetica,sans-serif;font-size:12px;font-weight:normal;font-style:normal;text-decoration:none;background-color:white;stroke:black;stroke-width:2}.mscgenjs__chart path, .mscgenjs__chart rect{fill:none}.mscgenjs__chart .label-text-background{fill:white;stroke:white;stroke-width:0}.mscgenjs__chart .bglayer{fill:white;stroke:white;stroke-width:0}.mscgenjs__chart line{}.mscgenjs__chart .return, .mscgenjs__chart .comment{stroke-dasharray:5,3}.mscgenjs__chart .inline_expression_divider{stroke-dasharray:10,5}.mscgenjs__chart text{color:inherit;stroke:none;text-anchor:middle}.mscgenjs__chart text.anchor-start{text-anchor:start}.mscgenjs__chart .arrow-marker{overflow:visible}.mscgenjs__chart .arrow-style{stroke-width:1}.mscgenjs__chart .arcrow, .mscgenjs__chart .arcrowomit, .mscgenjs__chart .emphasised{stroke-linecap:butt}.mscgenjs__chart .arcrowomit{stroke-dasharray:2,2}.mscgenjs__chart .box, .mscgenjs__chart .entity{fill:white;stroke-linejoin:round}.mscgenjs__chart .inherit{stroke:inherit;color:inherit}.mscgenjs__chart .inherit-fill{fill:inherit}.mscgenjs__chart .watermark{font-size:48pt;font-weight:bold;opacity:0.14}.mscgenjs__chart text.entity-text{font-weight:bold;}.mscgenjs__chart text.return-text{font-style:italic}.mscgenjs__chart path.note{fill:
```

**Comment by natecriss** [comment]
Additional information we have observed the same issue using the SIP plugin for both Kibana/ES 6.8 and 7.1.1.

**Comment by Rakesh100908** [comment]
Could you please verify the IP and Port being from tribenode.json ?

**Comment by natecriss** [comment]
It is set to the wrong IP address for sure... should it be the Kibana/ES server and is port 5555 correct?

**Comment by natecriss** [comment]
I don't have a service listening on 5555 either...

**Comment by Rakesh100908** [comment]
It should be IP of bwlogcollector application which is required for Call Flow.
Port 5555 should be ok.

**Comment by natecriss** [comment]
Thank you for your help!

changing the ip address in
/usr/share/kibana/plugins/sip/tribenode.js to the IP address of the bwlogcollector resolved the issue.
