### ISSUE TITLE
SIP Sequence not rendering

### ISSUE THREAD

**Issue by kdotson3263k** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#91]
Hello,

I am on Elastic/kibana Version: 6.6.2 and using:
XSIEvent-2.4.0_K_6.6.2.zip
SIP_2.4.0_K_6.6.2.zip

SIP Call Correlation ID Utility and ID search work fine and display the logs, but when I click to get the SIP Sequence and/or use the SIP Sequence query, nothing is rendering.  This seems to be intermittent although currently, I am not able to get anything to render.

 I am not seeing any glaring errors in the Kibana logs.  

Any help will be appreciated.

**Comment by gokulbsft** [comment]
Can you check if the logcollector application is running properly (port 5555 should be up) and also verify that the file tribenode.json which is located inside plugins/sip contains the IP of logcollector?

**Comment by kdotson3263k** [comment]
Yes it looks like it is all set up correctly (ips removed below) and everything except the sequence rendering is working.:

On kibana node:
I am not sure why I have this in 3 spots, but they are all the same and it is using the fqdn, not the ip, is that ok?

cat /etc/kibana/tribenode.json
"javaClient": "XXX:5555"
 cat /usr/share/kibana/plugins/sip/tribenode.json
{"javaClient": "XXX:5555"}
cat /usr/share/kibana/plugins/xsi_event/tribenode.json
"javaClient": "XXX:5555"

 telnet XXX 5555
Trying XXX..
Connected to XXX.
Escape character is '^]'.
^]
telnet> close
Connection closed.



on the tribe node server:
netstat -plntu | grep 5555
tcp6       0      0 :::5555                 :::*                    LISTEN      9479/java

**Comment by kdotson3263k** [comment]
If there a timeout for the SIP sequence?  It looks like this may be a time of day/utilization issue.

**Comment by pgawali-broadsoft** [comment]
Is there a timeout for the SIP sequence?
-No

you can verify our logcollector is processing properly using following request?
<LogcollectorIP>:<Port>/sipCallFlow?id=<CorrelationID>&index=bwlog*

if there is no response that mean your log-collector is not working as excepted. Kindly make sure log collector reachable from kibana host and at bwlogreciever call-sequence templates is executed.

**Comment by kdotson3263k** [comment]
Is this a curl command?

LogcollectorIP : Port/sipCallFlow?id= CorrelationID &index=bwlog*

**Comment by kdotson3263k** [comment]
The curl command works every time.  But the "Fetch" button and/or clicking the Hyperlink in the completed log output is hit and miss.  I can usually get the sequence diagram to render after repeatedly clicking the "Fetch" button.

**Comment by sdetwiler85** [comment]
I am having this same issue. The fetch does not work consistently, and never on the first few pushes. Is it possible that the diagram is taking too long to render? I also cannot get the download buttons to work, the downloads contain a tiny black empty box.

**Comment by pgawali-broadsoft** [comment]
Is it possible that the diagram is taking too long to render? 
>> Yes , if call flow is big it might take few seconds to render.
 I also cannot get the download buttons to work
>> Looks like issue to should be fixed in coming release.
